import { prisma } from '@/lib/prisma';
import { getMessengerCustomerName, sendMessengerMessage, sendMessengerQuickReplies } from '@/lib/messenger';

const CLASSES: Record<string, string> = {
  ai_golden: 'AI Golden Package Class',
  golden: 'Golden Package Class',
  speaking: 'Speaking Class',
  hsk: 'HSK Class',
};

// Fixed content from the supplied GESC reference document; never generated by AI.
const COURSE_DETAILS: Record<string, string> = {
  ai_golden: `🎓 GESC AI Golden Package Class\n\nGESC ကိုယ်ပိုင်သင်ရိုးကို အခြေခံပြီး Teacher + AI Technology ပေါင်းစပ်သင်ကြားပေးတဲ့ အတန်းဖြစ်ပါတယ်ရှင့်။\n\n• Level စုစုပေါင်း ၈ ခုရှိပါတယ်။\n• Level တစ်ခုလျှင် ၁ လ + ၁ ပတ်ခန့်၊ Level ၈ ခုလုံးအတွက် ၁ နှစ်ဝန်းကျင် ကြာမြင့်ပါတယ်။\n• AI ဖြင့် အသံထွက်၊ Chinese Character၊ Stroke Order၊ Writing နှင့် Speaking ကို Instant Feedback ဖြင့် လေ့ကျင့်နိုင်ပါတယ်။\n• GESC AI App မှ AI Self-Study၊ AI Exam နှင့် HSK Level 1–6 အထိ လေ့လာနိုင်ပါတယ်။\n• အတန်းတက်နေစဉ် ၁ နှစ်အထိ AI Self-Study၊ AI Exam နှင့် GESC Student Account များ အခမဲ့ရရှိပါတယ်။ အတန်းရပ်နားပါက အဆိုပါ Account များကို အသုံးပြုခွင့်မရှိတော့ပါ။\n• Level ၈ ခုလုံးပြီးဆုံးပါက ဘွဲ့အခမ်းအနား၊ သင်တန်းဆင်းလက်မှတ်နှင့် Job Interview အခွင့်အရေးများ ရရှိနိုင်ပါတယ်။\n\n💰 သင်တန်းကြေး\nLevel တစ်ခုလျှင် 280,000 ကျပ်\n• Level 1–5: 1,310,000 ကျပ် (Cashback 90,000)\n• Level 6–8: 780,000 ကျပ် (Cashback 60,000)\n• Level ၈ ခုလုံး: 2,060,000 ကျပ် (Cashback 180,000)`,
  golden: `🎓 GESC Golden Package Class\n\nတရုတ်ဘာသာစကားကို အခြေခံမှစတင်ပြီး Reading, Writing, Listening နှင့် Speaking ကို လုပ်ငန်းခွင်အထိ အသုံးချနိုင်သည့်အဆင့်ရောက်အောင် စနစ်တကျ သင်ကြားပေးတဲ့ အတန်းဖြစ်ပါတယ်ရှင့်။\n\n• Level စုစုပေါင်း ၈ ခုရှိပါတယ်။\n• Level တစ်ခုလျှင် ၁ လကျော်ခန့် ကြာမြင့်ပါတယ်။\n• Online Class Only ဖြစ်ပါတယ်။\n• တရုတ်စာအခြေခံမရှိသူများလည်း စတင်တက်ရောက်နိုင်ပါတယ်။\n• Level မြင့်လာပါက ဆရာ/ဆရာမနှင့် အတန်းချိန် အပြောင်းအလဲရှိနိုင်ပါတယ်။\n• Level ၈ ခုလုံးပြီးဆုံးပါက ဘွဲ့အခမ်းအနား၊ သင်တန်းဆင်းလက်မှတ်နှင့် Job Interview အခွင့်အရေးများ ရရှိနိုင်ပါတယ်။\n\n💰 သင်တန်းကြေး\nLevel တစ်ခုလျှင် 250,000 ကျပ်\n• Level 1–5: 1,160,000 ကျပ် (Cashback 90,000)\n• Level 6–8: 690,000 ကျပ် (Cashback 60,000)\n• Level ၈ ခုလုံး: 1,820,000 ကျပ် (Cashback 180,000)`,
  speaking: `🗣️ GESC Speaking Class (Regular Class)\n\nSpeaking Level 1 မှ Level 8 အထိ စုစုပေါင်း ၈ ခုရှိပါတယ်ရှင့်။ Speaking ပိုင်းကို အဓိကထားလေ့ကျင့်လိုသူများနှင့် အလုပ်/ကျောင်းတစ်ဖက်ဖြင့် အချိန်မအားလပ်သူများအတွက် အဆင်ပြေပါတယ်။\n\n• တရုတ်စာအခြေခံမရှိသူများလည်း Speaking Level 1 မှ စတင်နိုင်ပါတယ်။\n• Speaking မှ Golden Package သို့ ပြောင်းလိုပါက Speaking Level 1 မှ Writing ပိုင်းပါ လေ့ကျင့်ထားရန်လိုအပ်ပါတယ်။\n• Level တစ်ခုစီ ပြီးဆုံးတိုင်း စာမေးပွဲဖြေနိုင်သလို မဖြေဘဲ နောက် Level သို့ ဆက်တက်နိုင်ပါတယ်။\n• Level ၈ ခုလုံးပြီးဆုံးပါက PDF Certificate နှင့် Job Interview အခွင့်အရေးများ ရရှိနိုင်ပါတယ်။\n• Monday–Thursday: ၁ လခွဲခန့်\n• Saturday & Sunday: ၂ လကျော်ခန့်\n• Sunday Only: ၃ လခန့်\n\n💰 သင်တန်းကြေး\n• Level 1: 160,000 ကျပ်\n• Level 2–8: Level တစ်ခုလျှင် 130,000 ကျပ်\n• Level Test ဖြေပြီး Level အမြင့်မှစသူများအတွက် Entrance Fee 40,000 ကျပ် ထပ်မံကျသင့်ပါတယ်။\n• ဘေးလွယ်အိတ်၊ ဘောပင်အိတ်၊ ဖတ်/ရေးစာအုပ်၊ ဘောပင်၊ Color Pen နှင့် GESC Polo Shirt ပါဝင်ပါတယ်။`,
  hsk: `📚 HSK Class\n\nHSK (Hanyu Shuiping Kaoshi) သည် နိုင်ငံတကာအသိအမှတ်ပြု တရုတ်ဘာသာစကားအရည်အချင်းစစ် စာမေးပွဲဖြစ်ပါတယ်ရှင့်။\n\nတရုတ်နိုင်ငံမှ ထုတ်ဝေထားသော 《标准教程》 (Standard Course) သင်ရိုးစာအုပ်ဖြင့် HSK စာမေးပွဲအတွက် စနစ်တကျ ပြင်ဆင်သင်ကြားပေးပါတယ်။\n\n• နေ့စဉ်ဘဝတွင် အသုံးများသော တရုတ်စကားလုံးများ\n• ဝါကျများနှင့် Grammar Patterns\n• တရုတ်ယဉ်ကျေးမှု အခြေခံဗဟုသုတ\n• HSK မေးခွန်းပုံစံများနှင့် မေးခွန်းဟောင်းများ\n\n💰 HSK Class သင်တန်းကြေးနှင့် လက်ရှိအတန်းချိန်ကို Admin Team မှ စစ်ဆေးပြီး ပြန်လည်အကြောင်းကြားပေးပါမယ်ရှင့်။`,
};

const FAQ_DETAILS: Record<string, string> = {
  course_types: 'GESC တွင် လက်ရှိဖွင့်လှစ်ထားသော သင်တန်းများမှာ —\n\n(1) Ai Golden Package Class\n(2) Golden Package Class\n(3) Speaking Class\n(4) HSK Class\n\nတို့ ရှိပါတယ်ရှင့်။ ဘယ်အတန်းအကြောင်းလေးရှင်းပြပေးရမလဲရှင့်။',
  age: '👤 အသက် (၁၂) နှစ်အထက် ကျောင်းသား/ကျောင်းသူများသည် GESC သင်တန်းများကို စတင်တက်ရောက်နိုင်ပါတယ်ရှင့်။',
  level_test: '📝 အရင်က တရုတ်စာသင်ဖူးပြီး အခြေခံမှပြန်မတက်လိုသူများ၊ သို့မဟုတ် GESC ကျောင်းသားဟောင်းအနေဖြင့် ၃ လကျော်နားထားသူများသည် Level Test ဖြေဆိုနိုင်ပါတယ်ရှင့်။ ဖုန်းခေါ်ဆို၍ Speaking Test ဖြေဆိုရပြီး အမည်၊ ဖုန်းနံပါတ်နှင့် အမြဲအားလပ်နိုင်မည့်အချိန်ကို Admin Team ထံပေးပို့ရပါမယ်။ ပုံမှန်အားဖြင့် ၁ ပတ်ခန့် စောင့်ဆိုင်းရနိုင်ပြီး Level Test Fee သည် 10,000 ကျပ် ဖြစ်ပါတယ်ရှင့်။ Test ဖြေပြီးနောက် သင်တန်းတက်ရောက်ဖြစ်/မဖြစ်ပေါ်မူတည်၍ Fee ပြန်အမ်းမည်မဟုတ်ပါ။',
  differences: '🎓 Golden Package Class သည် Reading, Writing, Listening နှင့် Speaking အားလုံးကို စနစ်တကျလေ့လာလိုသူများအတွက် Online Class ဖြစ်ပါတယ်။\n\n🤖 AI Golden Package Class သည် Golden သင်ရိုးကို အခြေခံပြီး Teacher + AI Technology ဖြင့် Speaking၊ အသံထွက်နှင့် Writing ကို ထပ်မံလေ့ကျင့်နိုင်ပါတယ်။\n\n🗣️ Speaking Class သည် Speaking ကို အဓိကထားလိုသူများနှင့် စနေ/တနင်္ဂနွေ၊ Sunday Only ကဲ့သို့ အားလပ်ချိန်အလိုက် ဖြည်းဖြည်းလေ့လာလိုသူများအတွက် သင့်တော်ပါတယ်။\n\nGolden နှင့် AI Golden ကို Level ၈ ခုလုံးပြီးဆုံးပါက ဘွဲ့အခမ်းအနား Certificate ရရှိနိုင်ပြီး Speaking Level ၈ ခုလုံးပြီးဆုံးပါက PDF Certificate ရရှိနိုင်ပါတယ်။ Class သုံးမျိုးစလုံး Level ၈ ခုလုံးပြီးဆုံးပါက Job Interview အခွင့်အရေးများ ရရှိနိုင်ပါတယ်ရှင့်။',
  rules: '📜 သင်တန်းအပ်နှံပြီးနောက် သင်တန်းကြေးပြန်အမ်းပေးမည်မဟုတ်ပါရှင့်။ လုံးဝမတက်ရသေးပါက ၁ နှစ်အတွင်း ပြန်တက်နိုင်ပြီး တက်ရောက်ပြီးနောက် နားထားပါက ၃ လအတွင်း ပြန်တက်နိုင်ပါတယ်။\n\nအခြားအတန်းသို့ပြောင်းလိုပါက တက်ရောက်ထားသည့်ရက်ပေါ်မူတည်၍ အတန်းပြောင်းကြေး ကျသင့်နိုင်ပါတယ်။ လုံးဝမတက်ရသေးပါက အခြားသူထံ ၆ လအတွင်း သင်တန်းကြေးလွှဲပေးနိုင်သော်လည်း လွှဲပြောင်းလက်ခံသူက ထပ်မံလွှဲပေးမရပါ။ Golden Package Cashback ဖြင့်ကြိုတင်အပ်နှံထားသော Level များကို လွှဲလက်ခံသူသည် မူလ Cashback အကျိုးခံစားခွင့်မရပါရှင့်။',
  registration: '®️✍️ Registration ပြုလုပ်ရန်အတွက် အောက်ပါအချက်အလက်များကို ဖြည့်ပေးပါရှင့်။\n\n1. အမည်\nEnglish လို ရေးပေးပါရှင့်။\n\n2. ဖုန်းနံပါတ်\n📌 Online Class အပ်နှံသူများအနေဖြင့် Telegram / Viber အသုံးပြုနိုင်သော ဖုန်းနံပါတ်ကို ပေးပေးပါရှင့်။\n📌 On Campus Class အပ်နှံသူများအနေဖြင့် ဖုန်းနံပါတ်ပေးပေးရုံဖြင့် ရပါတယ်ရှင့်။\n\n3. လိပ်စာ\nလက်ရှိ ပြည်ပရောက်နေသူများအနေဖြင့် မြန်မာနိုင်ငံတွင် နေထိုင်ခဲ့သည့် လိပ်စာကို ပေးပေးပါရှင့်။\n\n4. မွေးနေ့အပြည့်အစုံ\n\n5. မှတ်ပုံတင်နံပါတ် အပြည့်အစုံ\n\n📌 မှတ်ချက် – Registration စာရင်းသွင်းခြင်းသည် သင်တန်းကြေးပေးသွင်းပြီးမှသာ Confirm ဖြစ်ပါမည်ရှင့်။\n\nအထက်ပါအချက်အလက်များကို Admin Team မှသာ Facebook Page Inbox တွင် ဆက်လက်လက်ခံဆောင်ရွက်ပေးပါမယ်ရှင့်။',
  spin_wheel: '🎡 သင်တန်းတက်နေစဉ် Level တစ်ခုအပ်နှံပြီး 3,000 ကျပ်ထပ်ပေးသွင်းပါက “ဗလာမပါ” Spin Wheel ကို ၁ ကြိမ်လှည့်နိုင်ပါတယ်ရှင့်။ 1 Ticket = 10,000 ကျပ်တန်ဖိုးဖြစ်ပြီး 1, 2, 5, 7 သို့မဟုတ် 10 Tickets ကံထူးနိုင်ပါတယ်။ Tickets ကို ငွေသားပြန်လဲမရဘဲ မိမိနောက် Level အတွက် Discount အဖြစ် သို့မဟုတ် ကျောင်းသားသစ်မိတ်ဆွေအတွက် အသုံးပြုနိုင်ပါတယ်။\n\nကျောင်းသားတစ်ယောက်လျှင် ၁ ကြိမ်သာလှည့်နိုင်ပြီး၊ ကျောင်းအပ်နှံမှုတစ်ကြိမ်အတွက် Ticket ၁ စောင်သာသုံးနိုင်ပါတယ်။ အပ်နှံပြီး ၇ ရက်အတွင်းမလှည့်ပါက Expire ဖြစ်ပြီး၊ ကံထူး Ticket များသည် ပေါက်သည့်နေ့မှ ၆ လအတွင်းသုံးရပါမယ်။ သင်တန်းကြေးအပြည့်ပေးသွင်းပြီးမှသာ Spin Wheel လှည့်ခွင့်ရရှိပါတယ်ရှင့်။',
  payment: 'ငွေလွှဲပြီးပါက ငွေလွှဲပြေစာ (Screenshot) ကို Transaction No. ပါရှိသည့်အတိုင်း ပြန်လည်ပေးပို့ပေးပါရှင့်။\n\n⚠️ Transaction No. မပါရှိသော Screenshot များကို ငွေလွှဲအတည်ပြုချက်အဖြစ် လက်ခံပေးမည်မဟုတ်ပါရှင့်။\n\n📌 ငွေလွှဲရာတွင် Note နေရာ၌ အောက်ပါအချက် ၂ ခုကို မဖြစ်မနေ ရေးပေးရပါမည် —\n\n👉 ကျောင်းသား/ကျောင်းသူအမည်\n👉 အပ်နှံသည့် Level\n\n⚠️ Note မရေးထားခြင်းကြောင့် ငွေလွှဲမှတ်တမ်းနှင့်ပတ်သက်ပြီး Account Error / ငွေလွှဲအတည်ပြုရာတွင် အခက်အခဲတစ်စုံတစ်ရာ ဖြစ်ပေါ်ပါက ငွေလွှဲသူဘက်မှ တာဝန်ယူဖြေရှင်းပေးရပါမယ်ရှင့်။\n\n📱 ငွေလွှဲပြီးပါက ဖုန်းထဲတွင် “GESC Student” App ကို Download ပြုလုပ်ပေးပါရှင့်။\n\n🧾 ငွေလွှဲပြေစာ (Voucher) ကို စစ်ဆေးပြီးနောက် Username နှင့် Password (PW) ကို ပြန်လည်ပေးပို့ပေးပါမယ်ရှင့်။\n\n📌 ငွေလွှဲပြီး (၁) ရက်အတွင်း Code No. မရရှိသေးပါက Login ဝင်ရောက်အသုံးပြုနိုင်ရန် Code No. လာရောက်တောင်းခံပေးပါရှင့်။\n\n‼️ အရေးကြီးမှတ်ချက်\nငွေလွှဲပြီးပါက မည်သည့်အကြောင်းကြောင့်မဆို သင်တန်းကြေး ပြန်လည်အမ်းပေးမည်မဟုတ်ပါရှင့်။',
  materials: '📦 On Campus Class အတွက် စာအုပ်နှင့် Uniform ကို အတန်းတက်ရောက်ချိန်တွင် ကျောင်းမှပေးပါတယ်ရှင့်။ ပြည်တွင်း Online Class အတွက် Delivery ဖြင့်ပို့ပေးပြီး လက်ခံသူအမည်၊ ဖုန်းနံပါတ်၊ လိပ်စာအတိအကျ၊ ကားဂိတ်မှပို့လိုပါက ကားဂိတ်အမည်နှင့် Uniform Size ကို Admin Team ထံပေးပို့ရပါမယ်။ ပြည်ပမှ Online Class အတွက် စာအုပ်များကို PDF File ဖြင့်ပေးပြီး အတန်းမစတင်မီဖွဲ့ပေးသော Group မှ သက်ဆိုင်ရာဆရာ/ဆရာမထံ ထုတ်ယူနိုင်ပါတယ်ရှင့်။',
};

const TOWNSHIPS = ['လှိုင်သာယာ', 'တာမွေ', 'လှည်းတန်း', 'လမ်းမတော်', 'ရွှေပြည်သာ', 'မြောက်ဥက္ကလာပ', 'မြေနီကုန်း', 'မြောက်ဒဂုံ'];

const FLOW_DEFAULTS: Record<string, string> = {
  class_info_prompt: 'လက်ရှိဖွင့်လှစ်ထားသော သင်တန်းများထဲမှ ရွေးချယ်နိုင်ပါတယ်ရှင့်။',
  faq_menu_prompt: 'မေးလိုသည့်အကြောင်းအရာကို ရွေးပေးပါရှင့်။',
  course_follow_up: '{{className}} အတွက် အတန်းချိန်ကို မေးမြန်းလိုပါက အောက်ပါခလုတ်ကို နှိပ်ပေးပါရှင့်။',
  select_class: 'တက်ရောက်လိုသည့် Class အမျိုးအစားကို ရွေးပေးပါရှင့်။',
  select_mode: '{{className}} ကို ဘယ်ပုံစံဖြင့် တက်ရောက်လိုပါသလဲရှင့်။',
  select_township: 'တက်ရောက်လိုသည့် မြို့နယ်ကို ရွေးပေးပါရှင့်။',
  pending_admin: 'Admin Team မှ လက်ရှိအတန်းလက်ခံနိုင်မှုနှင့် Class Schedule ကို စစ်ဆေးနေပါသည်ရှင့်။ ပြန်လည်အကြောင်းကြားပေးပါမယ်ရှင့်။',
  pending_admin_with_cancel: 'Admin Team မှ လက်ရှိအတန်းလက်ခံနိုင်မှုနှင့် Class Schedule ကို စစ်ဆေးနေပါသည်ရှင့်။ ဖျက်သိမ်းလိုပါက “Request ဖျက်မည်” button ကိုနှိပ်ပေးပါရှင့်။',
  schedule_offered: 'ပေးပို့ထားသော Class Schedule အတွက် “အဆင်ပြေပါတယ်” သို့မဟုတ် “အခြားအချိန်” button ကို ရွေးပေးပါရှင့်။',
  schedule_offered_with_cancel: 'ပေးပို့ထားသော Class Schedule အတွက် အဆင်ပြေမှုကို ရွေးပေးပါရှင့်၊ သို့မဟုတ် “Request ဖျက်မည်” button ကိုနှိပ်ပေးပါရှင့်။',
  selection_only: 'အတန်းချိန်မေးမြန်းရန်အတွက် ပေးထားသော button များထဲမှ ရွေးပေးပါရှင့်။',
  schedule_change_notice: 'အခြားအချိန်ကို Admin Team မှ ထပ်မံစစ်ဆေးပြီး ပြန်လည်အကြောင်းကြားပေးပါမယ်ရှင့်။',
  cancel_confirm: 'Schedule request ကို ဖျက်သိမ်းလိုသည်မှာ သေချာပါသလားရှင့်။',
  cancelled: 'Schedule request ကို ဖျက်သိမ်းပြီးပါပြီရှင့်။ နောက်ထပ်လိုအပ်သည်များကို အောက်ပါ menu မှ ရွေးချယ်နိုင်ပါတယ်ရှင့်။',
  cancel_aborted: 'Schedule request ကို မဖျက်သိမ်းတော့ပါရှင့်။ Admin Team မှ ပြန်လည်အကြောင်းကြားပေးပါမယ်ရှင့်။',
  request_created: 'ကျေးဇူးတင်ပါတယ်ရှင့်။ လက်ရှိအတန်းလက်ခံနိုင်မှုနှင့် Class Schedule ကို Admin Team မှ စစ်ဆေးပြီး ပြန်လည်အကြောင်းကြားပေးပါမယ်ရှင့်။',
  handoff: 'အတန်းချိန်အဆင်ပြေကြောင်း အတည်ပြုပေးလို့ ကျေးဇူးတင်ပါတယ်ရှင့်။ Registration အတွက် Admin Team မှ ဒီ Messenger မှတစ်ဆင့် ဆက်လက်ဆောင်ရွက်ပေးပါမယ်ရှင့်။',
  schedule_message_before: 'Admin Team မှ စစ်ဆေးပြီးပါပြီရှင့်။',
  schedule_message_after: 'အထက်ပါ အတန်းချိန် အဆင်ပြေပါသလားရှင့်။',
  unavailable_default: 'လက်ရှိတွင် အတန်းလက်ခံနိုင်ခြင်း မရှိသေးပါရှင့်။',
  unavailable_campus: 'ရွေးချယ်ထားသော မြို့နယ်တွင် လက်ရှိအတန်းမရရှိသေးပါရှင့်။',
  unavailable_online: 'လက်ရှိ Online Class အတန်းချိန် မရရှိသေးပါရှင့်။',
  faq_fallback: 'FAQ မေးခွန်းများကို အောက်ပါခလုတ်မှ ရွေးချယ်နိုင်ပါတယ်ရှင့်။',
  menu_home: '🏠 အစသို့',
  menu_schedule: '📅 အတန်းချိန်မေးရန်',
  menu_courses: '📚 သင်တန်းအကြောင်း',
  menu_faq: '❓ FAQ များ',
  menu_contact: '📞 ဆက်သွယ်ရန်',
  course_other: '📚 အခြားသင်တန်းများ',
  retry_township: '📍 နေရာပြောင်းရန်',
  retry_online: '💻 Online မေးရန်',
  retry_schedule: '📅 အချိန်ထပ်မေးရန်',
  mode_campus: '🏫 On Campus Class',
  mode_online: '💻 Online Class',
  request_cancel: '✖️ Request ဖျက်မည်',
  cancel_yes: '✅ ဟုတ်ကဲ့၊ ဖျက်မည်',
  cancel_no: '↩️ မဖျက်တော့ပါ',
  schedule_ok: '✅ အဆင်ပြေပါတယ်',
  schedule_change: '↩️ အခြားအချိန်',
  faq_course_types: '📚 သင်တန်းများ', faq_age: '👤 အသက်ကန့်သတ်ချက်', faq_level_test: '📝 Level Test',
  faq_differences: '⚖️ ကွာခြားချက်', faq_rules: '📜 စည်းကမ်းချက်များ', faq_registration: '✍️ Registration',
  faq_spin_wheel: '🎡 Spin Wheel', faq_payment: '💳 ငွေလွှဲနည်း', faq_materials: '📦 စာအုပ် / Uniform',
  class_ai_golden: 'AI Golden Package', class_golden: 'Golden Package Class', class_speaking: 'Speaking Class', class_hsk: 'HSK Class',
  township_0: 'လှိုင်သာယာ', township_1: 'တာမွေ', township_2: 'လှည်းတန်း', township_3: 'လမ်းမတော်',
  township_4: 'ရွှေပြည်သာ', township_5: 'မြောက်ဥက္ကလာပ', township_6: 'မြေနီကုန်း', township_7: 'မြောက်ဒဂုံ',
};

export function getEducationFlowText(bot: any, key: string) {
  const configured = (bot.educationFlowContent as Record<string, unknown> | null) || {};
  const value = configured[key];
  return typeof value === 'string' && value.trim() ? value.trim() : FLOW_DEFAULTS[key];
}

const flowText = getEducationFlowText;

function flowTextWithClass(bot: any, key: string, className: string) {
  return flowText(bot, key).replaceAll('{{className}}', className);
}

function educationMenuReplies(bot: any) {
  return [
    { title: flowText(bot, 'menu_courses'), payload: 'EDU_CLASS_INFO' },
    { title: flowText(bot, 'menu_schedule'), payload: 'EDU_START' },
    { title: flowText(bot, 'menu_faq'), payload: 'EDU_FAQ_MENU' },
    { title: flowText(bot, 'menu_contact'), payload: 'MENU_CONTACT_US' },
  ];
}

function faqButtons(bot: any) {
  return ['course_types', 'age', 'level_test', 'differences', 'rules', 'registration', 'spin_wheel', 'payment', 'materials']
    .map(id => ({ title: flowText(bot, `faq_${id}`), payload: `EDU_FAQ_${id}` }));
}

function classButtons(bot: any, prefix: 'EDU_INFO_' | 'EDU_CLASS_') {
  return Object.keys(CLASSES).map(id => ({ title: flowText(bot, `class_${id}`).slice(0, 20), payload: `${prefix}${id}` }));
}

function courseScheduleButtons(bot: any, classId: string) {
  return [
    { title: flowText(bot, `class_${classId}`).slice(0, 20), payload: `EDU_SCHEDULE_${classId}` },
    { title: flowText(bot, 'course_other').slice(0, 20), payload: 'EDU_CLASS_INFO' },
  ];
}

async function beginScheduleForClass(bot: any, token: string, senderId: string, classId: string) {
  const className = CLASSES[classId];
  if (!className) return true;
  await prisma.messengerSession.upsert({
    where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } },
    create: { botId: bot.id, messengerSenderId: senderId, state: 'education_select_mode', pendingData: { classType: className, selectedClassId: classId } },
    update: { state: 'education_select_mode', pendingData: { classType: className, selectedClassId: classId } },
  });
  await sendMessengerQuickReplies(token, senderId, flowTextWithClass(bot, 'select_mode', className), [
    { title: flowText(bot, 'mode_campus'), payload: 'EDU_MODE_CAMPUS' },
    { title: flowText(bot, 'mode_online'), payload: 'EDU_MODE_ONLINE' },
  ]);
  return true;
}

export async function isEducationBot(bot: any) {
  return bot.botCategory === 'education_registration';
}

export async function handleEducationPostback(bot: any, token: string, senderId: string, payload: string) {
  const existingSession = await prisma.messengerSession.findUnique({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } } });
  // A handoff belongs to this customer only. Do not let menu/postback events restart the bot.
  if (existingSession?.state === 'education_human_handoff') return true;
  if (existingSession?.state === 'education_pending_admin' && !payload.startsWith('EDU_CANCEL_')) {
    const requestId = (existingSession.pendingData as { requestId?: string } | null)?.requestId;
    if (requestId) await sendMessengerQuickReplies(token, senderId, flowText(bot, 'pending_admin_with_cancel'), [{ title: flowText(bot, 'request_cancel'), payload: `EDU_CANCEL_REQUEST_${requestId}` }]);
    else await sendMessengerMessage(token, senderId, flowText(bot, 'pending_admin_with_cancel'));
    return true;
  }
  if (existingSession?.state === 'education_schedule_offered' && !payload.startsWith('EDU_SCHEDULE_OK_') && !payload.startsWith('EDU_SCHEDULE_CHANGE_') && !payload.startsWith('EDU_CANCEL_')) {
    const requestId = (existingSession.pendingData as { requestId?: string } | null)?.requestId;
    if (requestId) await sendMessengerQuickReplies(token, senderId, flowText(bot, 'schedule_offered_with_cancel'), [
      { title: flowText(bot, 'schedule_ok'), payload: `EDU_SCHEDULE_OK_${requestId}` },
      { title: flowText(bot, 'schedule_change'), payload: `EDU_SCHEDULE_CHANGE_${requestId}` },
      { title: flowText(bot, 'request_cancel'), payload: `EDU_CANCEL_REQUEST_${requestId}` },
    ]);
    else await sendMessengerMessage(token, senderId, flowText(bot, 'schedule_offered_with_cancel'));
    return true;
  }
  if (payload === 'GET_STARTED' || payload === 'MENU_HOME' || payload === 'MAIN_MENU') {
    const welcomeMessage = typeof bot.messengerWelcomeMessage === 'string' && bot.messengerWelcomeMessage.trim()
      ? bot.messengerWelcomeMessage.trim()
      : 'မင်္ဂလာပါရှင့် G.E.S.C Chinese Language Center မှ ကြိုဆိုပါတယ်ရှင့်။ ဘာလေးများ ကူညီပေးရမလဲရှင့်။ တရုတ်ဘာသာစကားသင်တန်းများနှင့် ပတ်သက်ပြီး သိရှိလိုသည်များကို Message မှတစ်ဆင့် မေးမြန်းနိုင်ပြီး Admin Team မှ အမြန်ဆုံး ပြန်လည်ဖြေကြားပေးသွားပါမယ်ရှင့်။ ☎️ အမြန်ဆက်သွယ်လိုပါက- 09 255 544 131, 09 880 001 908 သို့ ဆက်သွယ်မေးမြန်းနိုင်ပါတယ်ရှင့်။';
    await sendMessengerQuickReplies(token, senderId, welcomeMessage, educationMenuReplies(bot));
    return true;
  }
  if (payload === 'EDU_CLASS_INFO') {
    await sendMessengerQuickReplies(token, senderId, flowText(bot, 'class_info_prompt'), classButtons(bot, 'EDU_INFO_'));
    return true;
  }
  if (payload === 'EDU_FAQ_MENU') {
    await sendMessengerQuickReplies(token, senderId, flowText(bot, 'faq_menu_prompt'), faqButtons(bot));
    return true;
  }
  if (payload.startsWith('EDU_FAQ_')) {
    const key = payload.slice('EDU_FAQ_'.length);
    const configured = (bot.educationFaqContent as Record<string, unknown> | null) || {};
    const customDetail = configured[key];
    const detail = typeof customDetail === 'string' && customDetail.trim() ? customDetail.trim() : FAQ_DETAILS[key];
    const partTwo = configured[`${key}_part_2`];
    if (!detail) return true;
    if (typeof partTwo === 'string' && partTwo.trim()) {
      await sendMessengerMessage(token, senderId, detail);
      await sendMessengerQuickReplies(token, senderId, partTwo.trim(), [{ title: flowText(bot, 'menu_faq'), payload: 'EDU_FAQ_MENU' }, { title: flowText(bot, 'menu_home'), payload: 'MENU_HOME' }]);
      return true;
    }
    await sendMessengerQuickReplies(token, senderId, detail, [{ title: flowText(bot, 'menu_faq'), payload: 'EDU_FAQ_MENU' }, { title: flowText(bot, 'menu_home'), payload: 'MENU_HOME' }]);
    return true;
  }
  if (payload.startsWith('EDU_INFO_')) {
    const classId = payload.slice('EDU_INFO_'.length);
    const className = CLASSES[classId];
    if (!className) return true;
    await prisma.messengerSession.upsert({
      where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } },
      create: { botId: bot.id, messengerSenderId: senderId, state: 'browsing', pendingData: { selectedClassId: classId } },
      update: { state: 'browsing', pendingData: { selectedClassId: classId } },
    });
    const configured = (bot.educationCourseContent as Record<string, unknown> | null) || {};
    const customDetail = configured[classId];
    const detail = typeof customDetail === 'string' && customDetail.trim()
      ? customDetail.trim()
      : COURSE_DETAILS[classId];
    const partTwo = configured[`${classId}_part_2`];
    if (!detail) return true;
    if (typeof partTwo === 'string' && partTwo.trim()) {
      await sendMessengerMessage(token, senderId, detail);
      await sendMessengerQuickReplies(token, senderId, `${partTwo.trim()}\n\n${flowTextWithClass(bot, 'course_follow_up', className)}`, courseScheduleButtons(bot, classId));
      return true;
    }
    await sendMessengerQuickReplies(token, senderId, `${detail}\n\n${flowTextWithClass(bot, 'course_follow_up', className)}`, courseScheduleButtons(bot, classId));
    return true;
  }
  if (payload === 'EDU_START') {
    const selectedClassId = (existingSession?.pendingData as { selectedClassId?: string } | null)?.selectedClassId;
    if (selectedClassId && CLASSES[selectedClassId]) return beginScheduleForClass(bot, token, senderId, selectedClassId);
    await prisma.messengerSession.upsert({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } }, create: { botId: bot.id, messengerSenderId: senderId, state: 'education_select_class' }, update: { state: 'education_select_class', pendingData: {} } });
    await sendMessengerQuickReplies(token, senderId, flowText(bot, 'select_class'), classButtons(bot, 'EDU_CLASS_'));
    return true;
  }
  if (payload.startsWith('EDU_SCHEDULE_') && !payload.startsWith('EDU_SCHEDULE_OK_') && !payload.startsWith('EDU_SCHEDULE_CHANGE_')) {
    return beginScheduleForClass(bot, token, senderId, payload.slice('EDU_SCHEDULE_'.length));
  }
  if (payload.startsWith('EDU_CLASS_')) {
    const classId = payload.slice('EDU_CLASS_'.length);
    return beginScheduleForClass(bot, token, senderId, classId);
  }
  if (payload === 'EDU_MODE_ONLINE') return createScheduleRequest(bot, token, senderId, 'Online Class');
  if (payload === 'EDU_MODE_CAMPUS') {
    const session = await prisma.messengerSession.findUnique({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } } });
    await prisma.messengerSession.update({ where: { id: session!.id }, data: { state: 'education_select_township' } });
    await sendMessengerQuickReplies(token, senderId, flowText(bot, 'select_township'), TOWNSHIPS.map((township, index) => ({ title: flowText(bot, `township_${index}`), payload: `EDU_TOWNSHIP_${index}` })));
    return true;
  }
  if (payload.startsWith('EDU_TOWNSHIP_')) return createScheduleRequest(bot, token, senderId, 'On Campus Class', TOWNSHIPS[Number(payload.slice('EDU_TOWNSHIP_'.length))]);
  if (payload.startsWith('EDU_RESELECT_TOWNSHIP_')) {
    const requestId = payload.slice('EDU_RESELECT_TOWNSHIP_'.length);
    const registration = await prisma.educationRegistration.findFirst({ where: { id: requestId, botId: bot.id, messengerSenderId: senderId, status: 'not_available', learningMode: 'On Campus Class' } });
    if (!registration?.classType) return true;
    await prisma.messengerSession.upsert({
      where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } },
      create: { botId: bot.id, messengerSenderId: senderId, state: 'education_select_township', pendingData: { classType: registration.classType } },
      update: { state: 'education_select_township', pendingData: { classType: registration.classType } },
    });
    await sendMessengerQuickReplies(token, senderId, flowText(bot, 'select_township'), TOWNSHIPS.map((township, index) => ({ title: flowText(bot, `township_${index}`), payload: `EDU_TOWNSHIP_${index}` })));
    return true;
  }
  if (payload.startsWith('EDU_RETRY_ONLINE_') || payload.startsWith('EDU_RETRY_SCHEDULE_')) {
    const isCampusRetry = payload.startsWith('EDU_RETRY_ONLINE_');
    const requestId = payload.slice(isCampusRetry ? 'EDU_RETRY_ONLINE_'.length : 'EDU_RETRY_SCHEDULE_'.length);
    const registration = await prisma.educationRegistration.findFirst({ where: { id: requestId, botId: bot.id, messengerSenderId: senderId, status: 'not_available', learningMode: isCampusRetry ? 'On Campus Class' : 'Online Class' } });
    if (!registration?.classType) return true;
    await prisma.messengerSession.upsert({
      where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } },
      create: { botId: bot.id, messengerSenderId: senderId, state: 'education_select_mode', pendingData: { classType: registration.classType } },
      update: { state: 'education_select_mode', pendingData: { classType: registration.classType } },
    });
    return createScheduleRequest(bot, token, senderId, 'Online Class');
  }
  if (payload.startsWith('EDU_SCHEDULE_OK_')) return handOffToHuman(bot, token, senderId, payload.slice('EDU_SCHEDULE_OK_'.length));
  if (payload.startsWith('EDU_SCHEDULE_CHANGE_')) {
    const id = payload.slice('EDU_SCHEDULE_CHANGE_'.length);
    await prisma.educationRegistration.updateMany({ where: { id, botId: bot.id, messengerSenderId: senderId }, data: { status: 'customer_requested_change' } });
    await prisma.messengerSession.updateMany({ where: { botId: bot.id, messengerSenderId: senderId }, data: { state: 'education_pending_admin', pendingData: { requestId: id } } });
    await sendMessengerMessage(token, senderId, flowText(bot, 'schedule_change_notice'));
    return true;
  }
  if (payload.startsWith('EDU_CANCEL_REQUEST_')) {
    const id = payload.slice('EDU_CANCEL_REQUEST_'.length);
    const request = await prisma.educationRegistration.findFirst({ where: { id, botId: bot.id, messengerSenderId: senderId, status: { in: ['pending_admin', 'customer_requested_change', 'schedule_offered'] } } });
    if (!request) return true;
    await sendMessengerQuickReplies(token, senderId, flowText(bot, 'cancel_confirm'), [
      { title: flowText(bot, 'cancel_yes'), payload: `EDU_CANCEL_CONFIRM_${id}` },
      { title: flowText(bot, 'cancel_no'), payload: `EDU_CANCEL_ABORT_${id}` },
    ]);
    return true;
  }
  if (payload.startsWith('EDU_CANCEL_CONFIRM_')) {
    const id = payload.slice('EDU_CANCEL_CONFIRM_'.length);
    const result = await prisma.educationRegistration.updateMany({ where: { id, botId: bot.id, messengerSenderId: senderId, status: { in: ['pending_admin', 'customer_requested_change', 'schedule_offered'] } }, data: { status: 'cancelled_by_customer' } });
    if (!result.count) return true;
    await prisma.messengerSession.updateMany({ where: { botId: bot.id, messengerSenderId: senderId }, data: { state: 'browsing', pendingData: {} } });
    await sendMessengerQuickReplies(token, senderId, flowText(bot, 'cancelled'), educationMenuReplies(bot));
    return true;
  }
  if (payload.startsWith('EDU_CANCEL_ABORT_')) {
    await sendMessengerMessage(token, senderId, flowText(bot, 'cancel_aborted'));
    return true;
  }
  return false;
}

async function createScheduleRequest(bot: any, token: string, senderId: string, learningMode: string, township?: string) {
  const session = await prisma.messengerSession.findUnique({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } } });
  const classType = (session?.pendingData as any)?.classType;
  const customerName = await getMessengerCustomerName(token, senderId);
  const request = await prisma.educationRegistration.create({ data: { botId: bot.id, messengerSenderId: senderId, customerName, classType, learningMode, township, status: 'pending_admin' } });
  await prisma.messengerSession.update({ where: { id: session!.id }, data: { state: 'education_pending_admin', pendingData: { requestId: request.id } } });
  await sendMessengerQuickReplies(token, senderId, flowText(bot, 'request_created'), [
    { title: flowText(bot, 'request_cancel'), payload: `EDU_CANCEL_REQUEST_${request.id}` },
  ]);
  return true;
}

async function handOffToHuman(bot: any, token: string, senderId: string, requestId: string) {
  const result = await prisma.educationRegistration.updateMany({ where: { id: requestId, botId: bot.id, messengerSenderId: senderId, status: 'schedule_offered' }, data: { status: 'handed_to_human', handedOffAt: new Date() } });
  if (!result.count) return true;
  await prisma.messengerSession.upsert({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } }, create: { botId: bot.id, messengerSenderId: senderId, state: 'education_human_handoff', pendingData: { requestId } }, update: { state: 'education_human_handoff', pendingData: { requestId } } });
  await sendMessengerMessage(token, senderId, flowText(bot, 'handoff'));
  return true;
}

export async function handleEducationText(bot: any, token: string, senderId: string, text: string) {
  const session = await prisma.messengerSession.findUnique({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } } });
  const state = session?.state;
  // Human-handoff conversations must remain silent, so the Page Inbox admin owns them.
  if (state === 'education_human_handoff') return;
  // Once a customer enters the schedule journey, only its buttons control the state.
  // This prevents typed FAQ keywords from interrupting or resetting an in-progress request.
  if (state === 'education_pending_admin') {
    const requestId = (session?.pendingData as { requestId?: string } | null)?.requestId;
    if (requestId) await sendMessengerQuickReplies(token, senderId, flowText(bot, 'pending_admin'), [{ title: flowText(bot, 'request_cancel'), payload: `EDU_CANCEL_REQUEST_${requestId}` }]);
    else await sendMessengerMessage(token, senderId, flowText(bot, 'pending_admin'));
    return;
  }
  if (state === 'education_schedule_offered') {
    const requestId = (session?.pendingData as { requestId?: string } | null)?.requestId;
    if (requestId) await sendMessengerQuickReplies(token, senderId, flowText(bot, 'schedule_offered'), [
      { title: flowText(bot, 'schedule_ok'), payload: `EDU_SCHEDULE_OK_${requestId}` },
      { title: flowText(bot, 'schedule_change'), payload: `EDU_SCHEDULE_CHANGE_${requestId}` },
      { title: flowText(bot, 'request_cancel'), payload: `EDU_CANCEL_REQUEST_${requestId}` },
    ]);
    else await sendMessengerMessage(token, senderId, flowText(bot, 'schedule_offered'));
    return;
  }
  if (['education_select_class', 'education_select_mode', 'education_select_township'].includes(state || '')) {
    await sendMessengerMessage(token, senderId, flowText(bot, 'selection_only'));
    return;
  }
  const normalized = text.toLowerCase();
  const greetingOnly = /^(hi|hello|hey|hi there|hello there|မင်္ဂလာပါ|မင်္ဂလာပါရှင့်)[!！.။\s]*$/u;
  if (greetingOnly.test(normalized.trim())) {
    await handleEducationPostback(bot, token, senderId, 'MENU_HOME');
    return;
  }
  const keywordFaq = ([
    ['course_types', ['သင်တန်းအမျိုးအစား', 'class type', 'courses', 'သင်တန်းတွေ']],
    ['age', ['အသက်', 'age', 'years old']],
    ['level_test', ['level test', 'leveltest', 'test', 'စာမေးပွဲ', 'ဘယ် level', 'အခြေခံရှိ']],
    ['differences', ['ကွာခြား', 'difference', 'golden package နဲ့', 'ai golden နဲ့']],
    ['rules', ['refund', 'စည်းကမ်း', 'ပြန်အမ်း', 'transfer']],
    ['registration', ['registration', 'register', 'ကျောင်းအပ်', 'အပ်ချင်']],
    ['spin_wheel', ['spin wheel', 'spinwheel', 'spin', 'ကံစမ်း', 'လှည့်']],
    ['payment', ['payment', 'ငွေလွှဲ', 'voucher', 'screenshot', 'transaction']],
    ['materials', ['uniform', 'စာအုပ်', 'delivery']],
  ] as [string, string[]][]).find(([, keywords]) => keywords.some(keyword => normalized.includes(keyword)));
  if (keywordFaq) {
    await handleEducationPostback(bot, token, senderId, `EDU_FAQ_${keywordFaq[0]}`);
    return;
  }
  const courseKeyword = ([
    ['ai_golden', ['ai golden', 'ai package']],
    ['golden', ['golden package', 'golden class']],
    ['speaking', ['speaking class', 'speaking level']],
    ['hsk', ['hsk class', 'hanyu shuiping']],
  ] as [string, string[]][]).find(([, keywords]) => keywords.some(keyword => normalized.includes(keyword)));
  if (courseKeyword) {
    await handleEducationPostback(bot, token, senderId, `EDU_INFO_${courseKeyword[0]}`);
    return;
  }
  if (['fee', 'price', 'သင်တန်းကြေး', 'fees', 'သင်တန်းအကြောင်း', 'class information', 'course information'].some(keyword => normalized.includes(keyword))) {
    await handleEducationPostback(bot, token, senderId, 'EDU_CLASS_INFO');
    return;
  }
  if (['schedule', 'အတန်းချိန်', 'class time'].some(keyword => normalized.includes(keyword))) {
    await handleEducationPostback(bot, token, senderId, 'EDU_START');
    return;
  }
  await sendMessengerQuickReplies(token, senderId, flowText(bot, 'faq_fallback'), educationMenuReplies(bot));
}
