import { prisma } from '@/lib/prisma';
import { sendMessengerMessage, sendMessengerQuickReplies } from '@/lib/messenger';

const CLASSES: Record<string, string> = {
  ai_golden: 'AI Golden Package Class',
  golden: 'Golden Package Class',
  speaking: 'Speaking Class',
  hsk: 'HSK Class',
};

// Fixed content from the supplied GESC reference document; never generated by AI.
const COURSE_DETAILS: Record<string, string> = {
  ai_golden: `🎓 GESC AI Golden Package Class\n\nGESC ကိုယ်ပိုင်သင်ရိုးကို အခြေခံပြီး Teacher + AI Technology ပေါင်းစပ်သင်ကြားပေးတဲ့ အတန်းဖြစ်ပါတယ်ရှင့်။\n\n• Level စုစုပေါင်း ၈ ခုရှိပါတယ်။\n• Level တစ်ခုလျှင် ၁ လ + ၁ ပတ်ခန့်၊ Level ၈ ခုလုံးအတွက် ၁ နှစ်ဝန်းကျင် ကြာမြင့်ပါတယ်။\n• AI ဖြင့် အသံထွက်၊ Chinese Character၊ Stroke Order၊ Writing နှင့် Speaking ကို Instant Feedback ဖြင့် လေ့ကျင့်နိုင်ပါတယ်။\n• အတန်းတက်နေစဉ် ၁ နှစ်အထိ AI Self-Study၊ AI Exam နှင့် GESC Student Account များ အခမဲ့ရရှိပါတယ်။\n\n💰 သင်တန်းကြေး\nLevel တစ်ခုလျှင် 280,000 ကျပ်\n• Level 1–5: 1,310,000 ကျပ် (Cashback 90,000)\n• Level 6–8: 780,000 ကျပ် (Cashback 60,000)\n• Level ၈ ခုလုံး: 2,060,000 ကျပ် (Cashback 180,000)`,
  golden: `🎓 GESC Golden Package Class\n\nတရုတ်ဘာသာစကားကို အခြေခံမှစတင်ပြီး လုပ်ငန်းခွင်အထိ အသုံးချနိုင်သည့်အဆင့် ရောက်ရှိအောင် စနစ်တကျ သင်ကြားပေးတဲ့ အတန်းဖြစ်ပါတယ်ရှင့်။\n\n• Level စုစုပေါင်း ၈ ခုရှိပါတယ်။\n• Level တစ်ခုလျှင် ၁ လကျော်ခန့် ကြာမြင့်ပါတယ်။\n• Online Class Only ဖြစ်ပါတယ်။\n• တရုတ်စာအခြေခံမရှိသူများလည်း စတင်တက်ရောက်နိုင်ပါတယ်။\n• Level ၈ ခုလုံးပြီးဆုံးပါက သင်တန်းဆင်းလက်မှတ်နှင့် Job Interview အခွင့်အရေးများ ရရှိနိုင်ပါတယ်။\n\n💰 သင်တန်းကြေး\nLevel တစ်ခုလျှင် 250,000 ကျပ်\n• Level 1–5: 1,160,000 ကျပ် (Cashback 90,000)\n• Level 6–8: 690,000 ကျပ် (Cashback 60,000)\n• Level ၈ ခုလုံး: 1,820,000 ကျပ် (Cashback 180,000)`,
  speaking: `🗣️ GESC Speaking Class (Regular Class)\n\nSpeaking Level 1 မှ Level 8 အထိ စုစုပေါင်း ၈ ခုရှိပါတယ်ရှင့်။ Speaking ပိုင်းကို အဓိကထားလေ့ကျင့်လိုသူများနှင့် အလုပ်/ကျောင်းတစ်ဖက်ဖြင့် အချိန်မအားလပ်သူများအတွက် အဆင်ပြေပါတယ်။\n\n• တရုတ်စာအခြေခံမရှိသူများလည်း Speaking Level 1 မှ စတင်နိုင်ပါတယ်။\n• Monday–Thursday: ၁ လခွဲခန့်\n• Saturday & Sunday: ၂ လကျော်ခန့်\n• Sunday Only: ၃ လခန့်\n\n💰 သင်တန်းကြေး\n• Level 1: 160,000 ကျပ်\n• Level 2–8: Level တစ်ခုလျှင် 130,000 ကျပ်\n• Level Test ဖြေပြီး Level အမြင့်မှစသူများအတွက် Entrance Fee 40,000 ကျပ် ထပ်မံကျသင့်ပါတယ်။`,
  hsk: `📚 HSK Class\n\nHSK (Hanyu Shuiping Kaoshi) သည် နိုင်ငံတကာအသိအမှတ်ပြု တရုတ်ဘာသာစကားအရည်အချင်းစစ် စာမေးပွဲဖြစ်ပါတယ်ရှင့်။\n\nတရုတ်နိုင်ငံမှ ထုတ်ဝေထားသော 《标准教程》 (Standard Course) သင်ရိုးစာအုပ်ဖြင့် HSK စာမေးပွဲအတွက် စနစ်တကျ ပြင်ဆင်သင်ကြားပေးပါတယ်။\n\n• နေ့စဉ်ဘဝတွင် အသုံးများသော တရုတ်စကားလုံးများ\n• ဝါကျများနှင့် Grammar Patterns\n• တရုတ်ယဉ်ကျေးမှု အခြေခံဗဟုသုတ\n• HSK မေးခွန်းပုံစံများနှင့် မေးခွန်းဟောင်းများ\n\n💰 HSK Class သင်တန်းကြေးနှင့် လက်ရှိအတန်းချိန်ကို Admin Team မှ စစ်ဆေးပြီး ပြန်လည်အကြောင်းကြားပေးပါမယ်ရှင့်။`,
};

const TOWNSHIPS = ['လှိုင်သာယာ', 'တာမွေ', 'လှည်းတန်း', 'လမ်းမတော်', 'ရွှေပြည်သာ', 'မြောက်ဥက္ကလာပ', 'မြေနီကုန်း', 'မြောက်ဒဂုံ'];

const menuReplies = [
  { title: '📅 အတန်းချိန်မေးရန်', payload: 'EDU_START' },
  { title: '📚 သင်တန်းအကြောင်း', payload: 'EDU_CLASS_INFO' },
  { title: '📞 ဆက်သွယ်ရန်', payload: 'MENU_CONTACT_US' },
];

export async function isEducationBot(bot: any) {
  return bot.botCategory === 'education_registration';
}

export async function handleEducationPostback(bot: any, token: string, senderId: string, payload: string) {
  const existingSession = await prisma.messengerSession.findUnique({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } } });
  // A handoff belongs to this customer only. Do not let menu/postback events restart the bot.
  if (existingSession?.state === 'education_human_handoff') return true;
  if (payload === 'GET_STARTED' || payload === 'MENU_HOME' || payload === 'MAIN_MENU') {
    await sendMessengerQuickReplies(token, senderId, 'G.E.S.C Chinese Language Center မှ ကြိုဆိုပါတယ်ရှင့်။ ဘာကူညီပေးရမလဲရှင့်။', menuReplies);
    return true;
  }
  if (payload === 'EDU_CLASS_INFO') {
    await sendMessengerQuickReplies(token, senderId, 'လက်ရှိဖွင့်လှစ်ထားသော သင်တန်းများထဲမှ ရွေးချယ်နိုင်ပါတယ်ရှင့်။', Object.entries(CLASSES).map(([id, label]) => ({ title: label.replace(' Package', '').slice(0, 20), payload: `EDU_INFO_${id}` })));
    return true;
  }
  if (payload.startsWith('EDU_INFO_')) {
    const classId = payload.slice('EDU_INFO_'.length);
    const configured = (bot.educationCourseContent as Record<string, unknown> | null) || {};
    const customDetail = configured[classId];
    const detail = typeof customDetail === 'string' && customDetail.trim()
      ? customDetail.trim()
      : COURSE_DETAILS[classId];
    if (!detail) return true;
    await sendMessengerQuickReplies(token, senderId, `${detail}\n\nလက်ရှိအတန်းချိန်ကို သိလိုပါက အောက်ပါခလုတ်ကိုနှိပ်ပေးပါရှင့်။`, [{ title: '📅 အတန်းချိန်မေးရန်', payload: 'EDU_START' }, { title: '🏠 အစသို့', payload: 'MENU_HOME' }]);
    return true;
  }
  if (payload === 'EDU_START') {
    await prisma.messengerSession.upsert({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } }, create: { botId: bot.id, messengerSenderId: senderId, state: 'education_select_class' }, update: { state: 'education_select_class', pendingData: {} } });
    await sendMessengerQuickReplies(token, senderId, 'တက်ရောက်လိုသည့် Class အမျိုးအစားကို ရွေးပေးပါရှင့်။', Object.entries(CLASSES).map(([id, label]) => ({ title: label.replace(' Package', '').slice(0, 20), payload: `EDU_CLASS_${id}` })));
    return true;
  }
  if (payload.startsWith('EDU_CLASS_')) {
    const classId = payload.slice('EDU_CLASS_'.length);
    if (!CLASSES[classId]) return true;
    await prisma.messengerSession.update({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } }, data: { state: 'education_select_mode', pendingData: { classType: CLASSES[classId] } } });
    await sendMessengerQuickReplies(token, senderId, 'Class ပုံစံကို ရွေးပေးပါရှင့်။', [{ title: '🏫 On Campus Class', payload: 'EDU_MODE_CAMPUS' }, { title: '💻 Online Class', payload: 'EDU_MODE_ONLINE' }]);
    return true;
  }
  if (payload === 'EDU_MODE_ONLINE') return createScheduleRequest(bot, token, senderId, 'Online Class');
  if (payload === 'EDU_MODE_CAMPUS') {
    const session = await prisma.messengerSession.findUnique({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } } });
    await prisma.messengerSession.update({ where: { id: session!.id }, data: { state: 'education_select_township' } });
    await sendMessengerQuickReplies(token, senderId, 'တက်ရောက်လိုသည့် မြို့နယ်ကို ရွေးပေးပါရှင့်။', TOWNSHIPS.map((township, index) => ({ title: township, payload: `EDU_TOWNSHIP_${index}` })));
    return true;
  }
  if (payload.startsWith('EDU_TOWNSHIP_')) return createScheduleRequest(bot, token, senderId, 'On Campus Class', TOWNSHIPS[Number(payload.slice('EDU_TOWNSHIP_'.length))]);
  if (payload.startsWith('EDU_SCHEDULE_OK_')) return handOffToHuman(bot, token, senderId, payload.slice('EDU_SCHEDULE_OK_'.length));
  if (payload.startsWith('EDU_SCHEDULE_CHANGE_')) {
    const id = payload.slice('EDU_SCHEDULE_CHANGE_'.length);
    await prisma.educationRegistration.updateMany({ where: { id, botId: bot.id, messengerSenderId: senderId }, data: { status: 'customer_requested_change' } });
    await sendMessengerMessage(token, senderId, 'အခြားအချိန်ကို Admin Team မှ ထပ်မံစစ်ဆေးပြီး ပြန်လည်အကြောင်းကြားပေးပါမယ်ရှင့်။');
    return true;
  }
  return false;
}

async function createScheduleRequest(bot: any, token: string, senderId: string, learningMode: string, township?: string) {
  const session = await prisma.messengerSession.findUnique({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } } });
  const classType = (session?.pendingData as any)?.classType;
  const request = await prisma.educationRegistration.create({ data: { botId: bot.id, messengerSenderId: senderId, classType, learningMode, township, status: 'pending_admin' } });
  await prisma.messengerSession.update({ where: { id: session!.id }, data: { state: 'education_pending_admin', pendingData: { requestId: request.id } } });
  await sendMessengerQuickReplies(token, senderId, 'ကျေးဇူးတင်ပါတယ်ရှင့်။ လက်ရှိအတန်းလက်ခံနိုင်မှုနှင့် Class Schedule ကို Admin Team မှ စစ်ဆေးပြီး ပြန်လည်အကြောင်းကြားပေးပါမယ်ရှင့်။', [{ title: '🏠 အစသို့', payload: 'MENU_HOME' }]);
  return true;
}

async function handOffToHuman(bot: any, token: string, senderId: string, requestId: string) {
  const result = await prisma.educationRegistration.updateMany({ where: { id: requestId, botId: bot.id, messengerSenderId: senderId, status: 'schedule_offered' }, data: { status: 'handed_to_human', handedOffAt: new Date() } });
  if (!result.count) return true;
  await prisma.messengerSession.upsert({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } }, create: { botId: bot.id, messengerSenderId: senderId, state: 'education_human_handoff', pendingData: { requestId } }, update: { state: 'education_human_handoff', pendingData: { requestId } } });
  await sendMessengerMessage(token, senderId, 'အတန်းချိန်အဆင်ပြေကြောင်း အတည်ပြုပေးလို့ ကျေးဇူးတင်ပါတယ်ရှင့်။ Registration အတွက် Admin Team မှ ဒီ Messenger မှတစ်ဆင့် ဆက်လက်ဆောင်ရွက်ပေးပါမယ်ရှင့်။');
  return true;
}

export async function handleEducationText(bot: any, token: string, senderId: string, text: string) {
  const session = await prisma.messengerSession.findUnique({ where: { botId_messengerSenderId: { botId: bot.id, messengerSenderId: senderId } } });
  const state = session?.state;
  // Human-handoff conversations must remain silent, so the Page Inbox admin owns them.
  if (state === 'education_human_handoff') return;
  await sendMessengerQuickReplies(token, senderId, 'အတန်းချိန်မေးမြန်းလိုပါက အောက်ပါခလုတ်ကိုနှိပ်ပေးပါရှင့်။', menuReplies);
}
